[package]
name = "rust_hackathon"
version = "0.1.0"
authors = ["Chris <chrisashby@gocardless.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.4"
rand = "0.7.2"
itertools = "0.8.2"
